apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-db
  namespace: camera-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-db
  template:
    metadata:
      labels:
        app: image-db
    spec:
      containers:
      - name: image-db
        image: image-db:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 30081
        volumeMounts:
        - name: image-storage
          mountPath: /app/images
      volumes:
      - name: image-storage
        persistentVolumeClaim:
          claimName: image-storage-pvc