apiVersion: v1
kind: Service
metadata:
  name: image-db-service
  namespace: camera-system
spec:
  type: NodePort
  ports:
  - port: 30081
    targetPort: 30081
    nodePort: 30081
  selector:
    app: image-db