apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-service
  namespace: camera-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera-service
  template:
    metadata:
      labels:
        app: camera-service
    spec:
      hostNetwork: true  # Required for camera access
      containers:
      - name: camera-service
        image: camera-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5555
        env:
        - name: BLOCKCHAIN_ENABLED
          value: "true"
        - name: BLOCKCHAIN_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: blockchain-credentials
              key: camera-service-key
        - name: BLOCKCHAIN_SERVICE_URL
          value: "http://blockchain-service:30083"
        - name: RPI_ZEROTIER_IP
          value: "172.23.67.130"
        - name: WINDOWS_ZEROTIER_IP
          value: "172.23.228.240"
        - name: SERVICE_PORT
          value: "5555"
        volumeMounts:
        - name: camera-device
          mountPath: /dev/video0
        - name: metrics-storage
          mountPath: /app/metrics
        securityContext:
          privileged: true  # Required for camera access
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
      volumes:
      - name: camera-device
        hostPath:
          path: /dev/video0
          type: CharDevice
      - name: metrics-storage
        persistentVolumeClaim:
          claimName: metrics-storage-pvc