apiVersion: v1
kind: Secret
metadata:
  name: email-credentials
  namespace: camera-system
type: Opaque
data:
  email: cGljdHVyZWNvbnRyb2xsZXJAZ21haWwuY29t  # Base64 encoded email
  password: eW91cl9wYXNzd29yZF9oZXJl  # Base64 encoded password
---
apiVersion: v1
kind: Secret
metadata:
  name: blockchain-credentials
  namespace: camera-system
type: Opaque
data:
  email-handler-key: eW91cl9ibG9ja2NoYWluX3ByaXZhdGVfa2V5  # Base64 encoded blockchain private key