apiVersion: v1
kind: Service
metadata:
  name: email-handler-service
  namespace: camera-system
spec:
  type: NodePort
  ports:
  - port: 30082
    targetPort: 30082
    nodePort: 30082
  selector:
    app: email-handler