apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics-storage-pvc
  namespace: camera-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard