apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
  namespace: camera-system
spec:
  type: NodePort
  ports:
  - port: 30083
    targetPort: 30083
    nodePort: 30083
  selector:
    app: blockchain-service