apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockchain-storage-pvc
  namespace: camera-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard